Add quick amount buttons to forms
zeriontech/zerion-wallet-extension pull request #521
Opened 2024-05-31 15:55 UTC by zerts

2024-06-14 10:15 UTC, everdimension commented
I think that `button`s inside a `label` do not make sense:
<img width="365" alt="image" src="https://github.com/zeriontech/zerion-wallet-extension/assets/5347023/e3c86133-cf58-429d-ae15-a66c1681b2c9">

2024-06-14 10:15 UTC, everdimension commented on src/ui/pages/SendForm/fieldsets/TokenTransferInput/TokenTransferInput.tsx
> +                  onClick={() => {
I think we should focus the input when quick amount is clicked

2024-06-14 10:18 UTC, everdimension commented on src/ui/shared/forms/QuickAmounts.tsx
> +  title,
`title` can be confused with the native `title` attribute. Why not `children`?

2024-06-14 10:18 UTC, everdimension commented on src/ui/ui-kit/FormFieldset/FormFieldset.tsx
> +              <UIText kind="small/regular" as="label" ref={labelRef}>
perhaps remove `as label`

2024-06-14 10:44 UTC, everdimension requested changes
See comments, all good otherwise:)

2024-06-14 11:18 UTC, zerts commented on src/ui/ui-kit/FormFieldset/FormFieldset.tsx
> +            <UIText kind="small/regular" as="label" ref={labelRef}>
Not sure if we need label here as well. However, will not change it here for now.

2024-06-26 19:20 UTC, everdimension approved these changes

2024-07-09 11:46 UTC, merged